<script lang="ts">
	import { session } from "$lib/stores/session";
	import { theme } from '$lib/stores/theme'; 
</script>

<div class="prose">
	<h1>Zondy's Randwich</h1>
	<p>
		Can't decide what to get? Tired of ordering the same sandwich every time?
		Try the <strong>randwich</strong>! We believe sandwiches should be exciting.
		Whether you're looking to mix up your usual lunch routine or just want
		something unexpected, the randwich is for you!
	</p>

	<h2 class="mt-0">How it works:</h2>
	<ol>
		<li>Create an account (recommended for tracking and saving your randwiches).</li>
		<li>Generate a sandwich from the Dashboard.</li>
		<li>Order it. Upload a picture of it. Eat it. Love it.</li>
		<li>Give it a review.</li>
	</ol>
	<p>
		You can create a randwich without an account, but creating an account will help you save your creations and track your progress!
	</p>

	<div>
		{#if $session?.user}
			<div class="border p-4 rounded-lg bg-gray-100">
				<h3 class="text-xl font-semibold mb-4 mt-0">You're logged in!</h3>
				<p>Welcome back! Ready to create your next randwich?</p>
				<div class="flex gap-4 mt-4">
					<a href="/dashboard" class="btn btn-primary text-base-100">Go to Dashboard</a>
				</div>
			</div>
		{:else}
			<div class="flex flex-col md:flex-row gap-6">
				<!-- Option A: Sign up or Log in -->
				<div class="border p-6 rounded-lg bg-blue-50 w-full md:w-1/2">
					<h3 class="text-xl font-semibold mb-4 mt-0">Option A: Create an Account <p class="inline text-sm text-gray-500"> (Recommended)</p></h3> 
					<p>Sign up to track your sandwich history and make it onto the leaderboard.</p>
					<div class="flex gap-4">
						<a href="/signup" class="btn btn-primary text-base-100 font-semibold">Sign Up</a>
						<a href="/login" class="btn text-base-100 font-semibold">Log In</a>
					</div>
				</div>

				<!-- Option B: Generate a Sandwich without an Account -->
				<div class="border p-6 rounded-lg bg-green-50 w-full md:w-1/2">
					<h3 class="text-xl font-semibold mb-4 mt-0">Option B: Just Create a Sandwich</h3>
					<p>If you just want to try creating a randwich without signing up, feel free to generate one!</p>
					<a href="/dashboard" class="btn btn-primary text-base-100 font-semibold">Generate a Sandwich</a>
				</div>
			</div>
		{/if}
	</div>

	<p class="mt-6">
		Your randwich's name is generated by AI based on the ingredients and
		the daily theme! (today's theme is <strong>{$theme ? $theme : ""}</strong>)
	</p>
	<p>
		Also check out the leaderboard to see how many randwiches you've eaten
		compared to others!
	</p>
</div>
