<script lang="ts">
	import { session } from "$lib/stores/session";
	import { theme } from '$lib/stores/theme'; 
</script>

<div class="prose">
	<h1>Zondy's Randwich</h1>
	<p>
		Can't decide what to get? Tired of ordering the same sandwich every time?
		Try the <strong>randwich</strong>! We believe sandwiches should be exciting.
		Whether you're looking to mix up your usual lunch routine or just want
		something unexpected, the randwich is for you!
	</p>

	<h2 class="mt-0">How it works:</h2>
	<ol>
		<li>Create an account.</li>
		<li>Generate a sandwich from the Dashboard.</li>
		<li>Order it. Upload a picture of it. Eat it. Love it.</li>
		<li>Give it a review.</li>
	</ol>
	<p class="flex items-center gap-4">
		{#if $session?.user}
			<a href="/dashboard" class="btn btn-primary text-base-100">Dashboard</a>
			<a href="/settings" class="btn text-base-100">Settings</a>
		{:else}
			<a href="/signup" class="btn btn-primary text-base-100">Sign Up</a>
			<a href="/login" class="btn text-base-100">Log In</a>
		{/if}
	</p>
	<p>
		Your randwich's name is generated by AI based on the ingredients and
		the daily theme! (today's theme is <strong>{$theme ? $theme : ""}</strong>)
	</p>
	<p>
		Also check out the leaderboard to see how many randwiches you've eaten
		compared to others!
	</p>
	
</div>
